{% set name = "bioimageio.core" %}
{% set version = "0.5.4post1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bioimageio.core-{{ version }}.tar.gz
  sha256: 9c9eff91c925c459d782374728b09148a1b3ead56d8cef04fe6b0299c6d279e1

build:
  number: 0
  noarch: python
  entry_points:
    - bioimageio = bioimageio.core.__main__:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - bioimageio.spec >=0.4
    - imageio >=2.5
    - numpy
    - python >=3.7
    - ruamel.yaml
    - tqdm
    - tifffile
    - typer
    - xarray

test:
  imports:
    - bioimageio
    - bioimageio.core
  commands:
    - pip check
    - bioimageio --help
  requires:
    - pip

about:
  home: https://github.com/bioimage-io/python-bioimage-io
  summary: Python functionality for the bioimage model zoo
  dev_url: https://github.com/bioimage-io/python-bioimage-io
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - constantinpape
    - FynnBe
    - k-dominik
    - oeway
