{% set name = "bioimageio.core" %}
{% set version = "0.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bioimageio.core-{{ version }}.tar.gz
  sha256: 58f4de260aba619607b577c4b6ba0195938bc0cf6e796bf390b53423951e7fbc

build:
  number: 0
  noarch: python
  entry_points:
    - bioimageio = bioimageio.core.__main__:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - bioimageio.spec >=0.4
    - imageio >=2.5
    - numpy
    - python >=3.7
    - ruamel.yaml
    - tqdm
    - typer
    # latest xarray conda package is broken, see https://github.com/conda-forge/bioimageio.core-feedstock/pull/15#issuecomment-1025107145
    # remove this pin once this issue is resolved
    - xarray <0.21

test:
  imports:
    - bioimageio
    - bioimageio.core
  commands:
    - pip check
    - bioimageio --help
  requires:
    - pip

about:
  home: https://github.com/bioimage-io/python-bioimage-io
  summary: Python functionality for the bioimage model zoo
  dev_url: https://github.com/bioimage-io/python-bioimage-io
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - constantinpape
    - FynnBe
    - k-dominik
    - oeway
